### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by mishra-tanay**
I have tried to port it to python3 . 
Would love to hear back from your side .

### CODE REVIEW

**Comment by AlanJAS** [comment]
When sound have problems of mixer, I usually continue without it instead raise SystemExit. In this game the sound is only an aggregate, it does not affect the gameplay.

**Comment by mishra-tanay** [comment]
Do I need to comment out the systemexit() calls ?

**Comment by quozl** [comment]
Thanks for thinking about this.

Reviewed.  I do not approve changing `os.path.join` to `+` unless you have a good reason.  What is the reason?
 
It doesn't run properly.  Please make sure it runs before making commits, so that "git bisect" can work properly for us.

I agree with @AlanJAS that your adding of SystemExit to the failure to load sound file seems a bit unusual.  Because of how we bundle activities, the chances of sound files being missing are very low, but if it happens it isn't a good enough reason to stop the program.  On the other hand, a missing image is something that should stop the program, and this is what it did before.

You may wish to read our [Python 3 Porting Guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md) and tell us if there's anything we need to change there.

Relates to https://github.com/sugarlabs/jump/issues/6.

**Comment by quozl** [comment]
Thanks for the port.

I now follow our [guide for reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers).

I've removed the mixer initialisation as it isn't needed.  I've removed the excess parentheses; perhaps you ran 2to3 twice by accident.  I've fixed a couple of tracebacks relating to assumptions about division returning integers;

```log
Traceback (most recent call last):
  File "jump.py", line 1012, in <module>
    main()
  File "jump.py", line 1009, in main
    MainWindow.SuperLooper()
  File "jump.py", line 747, in SuperLooper
    self.changePosition()
  File "jump.py", line 501, in changePosition
    if self.pressed==False and myMatrix[y][x]==1:
TypeError: list indices must be integers or slices, not float

Traceback (most recent call last):
  File "jump.py", line 1012, in <module>
    main()
  File "jump.py", line 1009, in main
    MainWindow.SuperLooper()
  File "jump.py", line 730, in SuperLooper
    self.checkValidMovement()
  File "jump.py", line 385, in checkValidMovement
    if(myMatrix[y][x]==0):
TypeError: list indices must be integers or slices, not float
```

I've rebased against current _master_ branch, which moved since your branch began.

I've pushed with `--force`.  You can see my changes by clicking on the [force-pushed]( https://github.com/sugarlabs/jump/compare/9a44bad1d40718336b6f138ccff05efbfb8d89fb..66a7dbbc6deafb27fdf79263323aa54bae46c417) link.

I've tested on Ubuntu 19.04 with Sugar 0.116 and will now merge.

**Pull request merged**
